### ISSUE TITLE
Error al ejecutar el programa (con nueva y antigua expresión regular).

### ISSUE THREAD

**Issue by AdCalzadilla** [alu0100775846/ProyectoTID#6]
# Error.
- Al ejecutar el programa en eclipse da los siguietes fallos:
  Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
  at java.util.ArrayList.rangeCheck(ArrayList.java:653)
  at java.util.ArrayList.get(ArrayList.java:429)
  at useful.regex.RegexFilenameHelper.getFilename(RegexFilenameHelper.java:13)
  at tvtropes_data_mining.TropesParser.parsePage(TropesParser.java:34)
  at tvtropes_data_mining.Main.main(Main.java:18)

**Comment by ghost** [comment]
Para ayudar sería conveniente saber el argumento que se le está pasando a RegexFilenameHelper.getFilename()

En principio debería de ser el filepath completo del HTML (ej "C:/Series/Lost.html") pero por el error parece que se le está pasando una cadena vacía.

**Comment by ghost** [comment]
Es posible que no esté configurada la dirección correcta a la carpeta que contiene las series (en mi caso "C:\Series"). La solución es cambiar el String literal en el código (en Main.java) para que apunte a la dirección de la carpeta correcta.
